name = "my-worker"
type = "webpack"

account_id = "2242258b4c7493340d896312214f0571"
workers_dev = true
route = "api.glaximo.com/*"
zone_id = "737c4a4b005e394e8bd9a8e5fef8db8b"
compatibility_date = "2021-12-13"

kv_namespaces = [
    { binding = "MY_KV", preview_id = "a202bdac32ca4ca1aee088bfd50c5881", id = "5e6fcfd219e8410b82b051e4ecee1b08" },
    { binding = "SOCIAL_MEDIA_KV", preview_id = "8778ef92330c4370858cb9601289a32b", id = "1d5dbca18a5f4f418e417c12746b6a89" }
]

[vars]
AUTH_SERVER = "https://east-bra-risk-connected.trycloudflare.com"
